name: "process-pr"
description: "internal"
author: "js6pak"
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
runs:
  using: 'node12'
  main: '../dist/index.js'
